# site properties and page defaults
title: Nobis Lab
subtitle: 
description: Our lab uses cutting edge techniques to take a neural circuit approach to study epilepsy, in particular seizure-related respiratory dysfunction and sudden unexpected death in epilepsy (SUDEP). Our goal is harness this knowledge to develop strategies to prevent SUDEP and treat epilepsy and its commorbidities. Toward this goal, we use a variety of approaches including electrophysiology, imaging, optogenetics, plethysmography, fiber photometry, calcium imaging, EEG and telemetry. 
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: william.p.nobis@vumc.org
  orcid: 0000-0002-2318-6077
  google-scholar: wWSXrvIAAAAJ
  github: wildbill12
  twitter: LabNobis
  youtube: 

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
